### ISSUE TITLE
Backup size question

### ISSUE THREAD

**Issue by shmox** [gilbertchen/duplicacy-cli#13]
It's not an issue, but i have a question:

I have backed up an angular.js application with hugh number of files and (sub)folders.

I have made the first backup, then i modified just a 1.15kb file in which i just modified a word (text string).
I have then made my second backup then i compared the repository size with the first backup and noticed that the difference is about 200kb or more.
I have made another test with -hash option but the difference in size is even higher, more than 1mb

My question is: Why the backup size is big even if my change is just a word change in 1.5kb  file ?
Is this an internal work of duplicacy ? I know that metadata are saved on backup but can it be optimized ?

**Please note that i have used compression level of 9**

_Sorry for my ugly english :-(_

**Comment by gilbertchen** [comment]
The default chunk size is 4M bytes, so if the modified file is smaller than that you won't see any benefit of deduplication.

That's because Duplicacy will keep packing files into a chunk until the chunk boundary mark is found.  You can think of this as if it would pack all files into a big tar file and then split the imaginary tar file into chunks.  When you run the backup without the -hash option, any modified files will be rescanned and packed as new chunks.  So in your case you would get a new 1.15kb chunk but the 200kb difference is likely due to the change in file list and metadata (which are also packed and split the same way as files).

When you use the -hash option, all files are rescanned and repacked, so the chunk containing the modified will be gone, replaced by one or maybe more new chunks, and since the average size of chunks is 4MB, you may get much larger size differences.

**Comment by shmox** [comment]
Ok thank you, is the metadata deduplicated too ?

**Comment by gilbertchen** [comment]
Yes.  There is an example at the end of the [Snapshot Format] section (https://github.com/gilbertchen/duplicacy-beta/blob/master/DESIGN.md#snapshot-format) showing that if no files have been changed, no chunks (including metadata chunks) will be uploaded.

**Comment by shmox** [comment]
Okay, i have made test comparison with borgbackup (with same compression level: zlib), the difference in size with borgbackup  is about 5kb with duplicacy it is 88kb, i think that all this size difference in size is comming from metadata, here is the stats of duplicacy:

Files: 1459 total, 70,209K bytes; 1 new, 733 bytes
File chunks: 15 total, 70,210K bytes; 1 new, 733 bytes, 360 bytes uploaded
Metadata chunks: 3 total, 310K bytes; 3 new, 310K bytes, **88K bytes uploaded**
All chunks: 18 total, 70,520K bytes; 4 new, 311K bytes, 88K bytes uploaded

As you can see the 88kb is the metadata, i don't know if the metadata chunks can be optimized ?

Thank you again, duplicacy can be a must for windows users when it will be final :+1:
