### ISSUE TITLE
S3 eventual consistency

### ISSUE THREAD

**Issue by warwickgrigg** [gilbertchen/duplicacy-cli#20]
Just wondering if S3's eventual consistency causes a problem. My understanding is that S3's rename is a copy followed by a delete, and that the delete part of that process is an "eventually" consistent operation. If a backup starts very soon after fossil collection ends, and if at the very end of the fossil collection a chunk rename (ie delete) operation starts, eventually becoming consistent at some later time, then the backup could think the chunk properly exists when actually S3 is in the process of converting it into fossil.  The second stage prune thinks the backup wasn't concurrent  so it would happily delete the fossil rather than converting it back to a proper chunk. Is that a possible scenario?

**Comment by gilbertchen** [comment]
This is indeed a problem.   For storages that can't guarantee strong consistency, we add an additional time of 12 hours when comparing the end time of the fossil collection step and the end time of a 'new' backup.  That is, the fossil deletion step can proceed only if there is a new backup that finishes 12 hours after the fossil collection step finishes.  Hopefully these 12 hours are enough for the deletions to propagate to every S3 server so that every later backup will see that the chunk has been deleted and re-upload it.

**Comment by gilbertchen** [comment]
This issue has been mentioned on **Duplicacy Forum**. There might be relevant details there:

https://forum.duplicacy.com/t/document-effect-of-storage-consistency-on-pruning/6631/1
