### ISSUE TITLE
Backup hanging with sftp

### ISSUE THREAD

**Issue by martinpengellyphillips** [gilbertchen/duplicacy-cli#34]
Am seeing the backup process hang without any information regarding any issues. This is over sftp.

For example, running a backup to a remote machine today, I checked output at 18:27 to see the process had appeared to hang at 17:27

```
2017-01-01 17:27:01.194 INFO UPLOAD_PROGRESS Skipped chunk 378 size 6580432, 17.11MB/s 04:17:29 0.6%
2017-01-01 17:27:01.491 INFO UPLOAD_PROGRESS Skipped chunk 379 size 11666325, 17.22MB/s 04:15:56 0.6%
2017-01-01 17:27:02.409 INFO UPLOAD_PROGRESS Skipped chunk 381 size 1115549, 17.07MB/s 04:18:09 0.6%
2017-01-01 17:27:03.311 INFO UPLOAD_PROGRESS Skipped chunk 382 size 5007440, 16.96MB/s 04:19:51 0.7%
```

Note that the remote host is still accessible and I can ssh in fine from the same machine running the backup.

**Comment by martinpengellyphillips** [comment]
I have re-run the backup with `-vss` now and it seems to be going through, but it would be good to know if not using `-vss` can cause hangs under Windows as well as how to better debug issues like this when they occur.

**Comment by gilbertchen** [comment]
Assuming you're running Duplicacy on Windows, I'm not sure if this is caused by an SFTP glitch or a hanging CreateFile call.  If this happens again, install [delve](https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md) and run `delve attach <pid>` and then `goroutines`.  If you see a uploadChunk goroutine it is probably the SFTP channel is blocking.

**Comment by martinpengellyphillips** [comment]
Thanks. Will do and report back if issue occurs again.
