### ISSUE TITLE
The snapshot ~ at revision 2 contains an error: The entry ~ appears before the entry ~

### ISSUE THREAD

**Issue by eshagh** [gilbertchen/duplicacy-cli#46]
Hey,

In testing a few different scenarios, I've come across an interesting problem: I am able to complete a backup/snapshot, but when running the subsequent one, it fails with the following message:

The snapshot data at revision 2 contains an error: The entry /Sources/� Sanity check_ Is WiMAX almost here and will it unlock the n...pdf appears before the entry /Sources/» Sanity check_ Is WiMAX almost here and will it unlock the n...pdf

In looking at this, it appears the files are duplicates and contain strange filenames (windows sourced). One solution is removing the duplicate, or correcting the filenames. However, knowing which files are problematic ahead of time is difficult and having to re-run the snapshot/backup job is time consuming. Do you have any suggestions? Have you seen this before?

Is it possible to edit the snapshot file (encrypted) to correct it or is my only option to try to fix the filename/duplicate problem, delete the snapshot, and try again?

Thanks!

**Comment by gilbertchen** [comment]
I tried to reproduce this bug but failed.  � is 0xFFFD and » is 0xBB so obviously » should appear before �.  Checked the source code but couldn't figure out under what condition it can be reversed.

Could you please post the directory listing of 'Sources' here?

Currently there is no way to fix this other than removing the snapshots (just remove the files under the snapshots dir on the storage).  But after you remove the problematic files the re-run will be much faster because it doesn't need to upload all those chunks again.

**Comment by eshagh** [comment]
As I deleted and renamed those files to proceed with testing, it occurred to me that I should preserve them for science (and reproducing this issue). I might be able to pull the directory from a separate backup. I will attempt to do so and post it.

**Comment by eshagh** [comment]
here we are: https://www.amazon.com/clouddrive/share/N87YXcJUcB9zQdKcDGdhBpggtLVwZNUF0qxGg5Ddqk6

There are two file duplicate pairs that triggered the error on separate occasions (corrected sequentially by deleting/renaming them):
- Zoom on XOHM...
- Sanity check_Is...

**Comment by gilbertchen** [comment]
These files are very helpful!  I really appreciate that!

The error was caused by invalid Unicode characters in filenames (`0x96`, `0x97`).  When the file list is serialized into json format, these characters were replaced by the Unicode replacement character `\uFFFD`.  Thus files are no longer in sorted order and the backup command bails out because of that.

Version 1.2.1 fixed this issue.  There are two changes: first is to preserve the invalid Unicode characters and second if files with `\uFFFD` in their names become unsorted it won't complain about it.

**Comment by eshagh** [comment]
I reran a backup job after correcting the last filename problem on 1.2.0, and it discovered another filename error elsewhere in the file system. Upgraded to 1.2.1 and duplicacy is proceeding with the backup job without correcting the filename error. I was worried that I would have to delete the snapshot again and start over, but that appears not to be the case. If the job completes I think this is confirmed fixed. I'll circle back when it's done running.

Thanks!

**Comment by eshagh** [comment]
Sorry for the delay, I can confirm 1.2.1 fixes the issue. Thank you!
